# Generate template specialisations for groupwise - these are the functions
# that are called from R.

# groups and summaries are defined in summarise.r
source("../R/summarise.r")

cpp_fun <- function(summary) {
  name <- paste("condense", tolower(summary), sep = "_")

  args <- paste("const List& x",
    "const NumericVector& z", "const NumericVector& weight",  sep = ", ")

  body <- paste("return condense(BinnedVectors(x), z, weight, ",
    "Summary", summaries[[summary]], ");", sep = "")

  paste("// [[Rcpp::export]]\n",
    "List ", name, "(", args, ") {\n",
    "  ", body, "\n}\n\n", sep = "")
}


groupwise <- readLines("condense.cpp")
split <- which(grepl("// -{40,}", groupwise))[1]
original <- groupwise[1:split]

writeLines(original, "condense.cpp")

cat("// Autogenerated by condense-gen.r\n", file = "condense.cpp", append = TRUE)
funs <- unlist(lapply(names(summaries), cpp_fun))
cat(funs, file = "condense.cpp", append = TRUE, sep = "")
