library(whisker)

# Generate template specialisations for groupwise - these are the functions
# that are called from R.

# groups and summaries are defined in summarise.r
source("../R/summarise.r")

template <- "
// [[Rcpp::export]]
List condense_{{name}}(const List& x, const NumericVector& z,
                       const NumericVector& weight, bool drop = false) {
  if (drop) {
    return sparse_condense(BinnedVectors(x), z, weight, Summary{{summary}});
  } else {
    return condense(BinnedVectors(x), z, weight, Summary{{summary}});
  }
}
"

cpp_fun <- function(summary) {
  whisker.render(template, list(
    name = tolower(summary),
    summary = summaries[[summary]]
  ))
}


groupwise <- readLines("condense.cpp")
split <- which(grepl("// -{40,}", groupwise))[1]
original <- groupwise[1:split]

writeLines(original, "condense.cpp")

cat("// Autogenerated by condense-gen.r\n", file = "condense.cpp", append = TRUE)
funs <- unlist(lapply(names(summaries), cpp_fun))
cat(funs, file = "condense.cpp", append = TRUE, sep = "")
