# Generate template specialisations for groupwise - these are the functions
# that are called from R.

# groups and summaries are defined in summarise-1d.r

combs <- expand.grid(group = names(groups), summary = names(summaries))

cpp_fun <- function(summary, group) {
  name <- paste("compute", tolower(summary), tolower(group), sep = "_")

  g_vars <- groups[[group]]
  g_args <- paste(g_vars, names(g_vars), collapse = ", ")
  s_args <- paste("const NumericVector&", c("x", "y", "weight"), collapse = ", ")
  args <- paste(s_args, ", ", g_args, sep = "")

  body <- paste("return summarise1d(y, weight, ",
    "Group", group, "(x, ", paste(names(g_vars), collapse = ", "), "), ",
    "Stat", summaries[[summary]], ");", sep = "")

  paste("// [[Rcpp::export]]\n",
    "NumericVector ", name, "(", args, ") {\n",
    "  ", body, "\n}\n\n", sep = "")
}


groupwise <- readLines("groupwise.cpp")
split <- which(grepl("// -{40,}", groupwise))[1]
original <- groupwise[1:split]

writeLines(original, "groupwise.cpp")

cat("// Autogenerated by groupwise-gen.r\n", file = "groupwise.cpp", append = TRUE)
funs <- mapply(cpp_fun, combs$summary, combs$group)
cat(funs, file = "groupwise.cpp", append = TRUE, sep = "")
