#include <Rcpp.h>
#include "group.hpp"
#include "summary.hpp"
using namespace Rcpp;

template<typename Group, typename Stat>
NumericVector summarise1d(const NumericVector& y, const NumericVector& weight, 
                        const Group& group, const Stat& stat) {
  int n_obs = group.size();

  const NumericVector& weight_ = (weight.size() > 0) ? weight : 
    rep(NumericVector::create(1), n_obs);
  const NumericVector& y_ = (y.size() > 0) ? y : 
    rep(NumericVector::create(1), n_obs);

  std::vector<Stat> stats;
  for(int i = 0; i < n_obs; ++i) {
    int bin = group.bin(i);

    if (bin >= stats.size()) {
      stats.insert(stats.end(), bin - stats.size(), stat);
    }

    stats[bin].push(y_[i], weight_[i]);
  }

  int n = stats.size();
  int m = stats[0].size();
  NumericMatrix res(n, m);
  for (int i = 0; i < n; ++i) {
    for (int j = 0; j < m; ++j) {
      res(i, j) = stats[i].compute(j);
    }
  }

  CharacterVector colnames(m);
  for (int j = 0; j < m; ++j) {
    colnames[j] = stats[0].name(j);
  }
  res.attr("dimnames") = List::create(CharacterVector::create(), colnames);

  return res;
}

// -----------------------------------------------------------------------------
// Autogenerated by summarise-1d-gen.r
// [[Rcpp::export]]
NumericVector summarise_count_breaks(const NumericVector& x, const NumericVector& y, const NumericVector& weight, NumericVector& breaks) {
  return summarise1d(y, weight, GroupBreaks(x, breaks), SummarySum(0));
}

// [[Rcpp::export]]
NumericVector summarise_count_fixed(const NumericVector& x, const NumericVector& y, const NumericVector& weight, double width, double origin) {
  return summarise1d(y, weight, GroupFixed(x, width, origin), SummarySum(0));
}

// [[Rcpp::export]]
NumericVector summarise_sum_breaks(const NumericVector& x, const NumericVector& y, const NumericVector& weight, NumericVector& breaks) {
  return summarise1d(y, weight, GroupBreaks(x, breaks), SummarySum(1));
}

// [[Rcpp::export]]
NumericVector summarise_sum_fixed(const NumericVector& x, const NumericVector& y, const NumericVector& weight, double width, double origin) {
  return summarise1d(y, weight, GroupFixed(x, width, origin), SummarySum(1));
}

// [[Rcpp::export]]
NumericVector summarise_mean_breaks(const NumericVector& x, const NumericVector& y, const NumericVector& weight, NumericVector& breaks) {
  return summarise1d(y, weight, GroupBreaks(x, breaks), SummaryMoments(1));
}

// [[Rcpp::export]]
NumericVector summarise_mean_fixed(const NumericVector& x, const NumericVector& y, const NumericVector& weight, double width, double origin) {
  return summarise1d(y, weight, GroupFixed(x, width, origin), SummaryMoments(1));
}

// [[Rcpp::export]]
NumericVector summarise_sd_breaks(const NumericVector& x, const NumericVector& y, const NumericVector& weight, NumericVector& breaks) {
  return summarise1d(y, weight, GroupBreaks(x, breaks), SummaryMoments(2));
}

// [[Rcpp::export]]
NumericVector summarise_sd_fixed(const NumericVector& x, const NumericVector& y, const NumericVector& weight, double width, double origin) {
  return summarise1d(y, weight, GroupFixed(x, width, origin), SummaryMoments(2));
}

// [[Rcpp::export]]
NumericVector summarise_median_breaks(const NumericVector& x, const NumericVector& y, const NumericVector& weight, NumericVector& breaks) {
  return summarise1d(y, weight, GroupBreaks(x, breaks), SummaryMedian());
}

// [[Rcpp::export]]
NumericVector summarise_median_fixed(const NumericVector& x, const NumericVector& y, const NumericVector& weight, double width, double origin) {
  return summarise1d(y, weight, GroupFixed(x, width, origin), SummaryMedian());
}

