# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bin_1d <- function(x, breaks) {
    .Call('bigvis_bin_1d', PACKAGE = 'bigvis', x, breaks)
}

bin_1d_fixed <- function(x, width, origin) {
    .Call('bigvis_bin_1d_fixed', PACKAGE = 'bigvis', x, width, origin)
}

#' Automatically zero-pads sample so that kernel trails off to zero.
#' @author Dirk Eddelbuettel, Romain Francois
#' @license GPL-2
convolve_1d <- function(x, kernel) {
    .Call('bigvis_convolve_1d', PACKAGE = 'bigvis', x, kernel)
}

convolve_2d <- function(sample, kernel) {
    .Call('bigvis_convolve_2d', PACKAGE = 'bigvis', sample, kernel)
}

